### ISSUE TITLE
Merge with upstream

### ISSUE THREAD

**Issue by hildjj** [hildjj/chained-emitter#3]
I haven't been tracking upstream, and now the merge is looking tough.  I think the right approach is to capture the changes on ChainedEmitter.js, reset to upstream, then carefully apply the changes.

**Comment by cantremember** [comment]
:+1:

i would appreciate if you did this

**Comment by cantremember** [comment]
... in your copious free time :smile:

**Comment by hildjj** [comment]
WONTFIX.  Deprecated this package in favor of `EventEmitter2.emitAsync`
